Update gradle.yml

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -70,15 +70,25 @@ jobs:
           username: ${{ secrets.EC2_USER }}
           key: ${{ secrets.EC2_SSH_KEY }}
           script: |
-            # Navigate to the app directory
+            # Ensure the app directory exists
+            mkdir -p app
             cd app
-            
+
+            # Check if docker-compose.yml exists in the app directory
+            if [ ! -f docker-compose.yml ]; then
+              echo "docker-compose.yml not found! Exiting."
+              exit 1
+            fi
+
             # Stop and remove existing containers
             docker-compose stop
             docker-compose rm -f
 
             # Remove old Docker image if exists
-            docker rmi gkstnaosi/zip-go:latest
+            docker rmi gkstnaosi/zip-go:latest || true
+
+            # Login to DockerHub
+            docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
 
             # Pull the latest Docker image from DockerHub
             docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/zip-go:latest
